name = "halaltensura"
mc_version = "1.21.1"

[jar]
type = "neoforge"
loader = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "tr-ancient-artifacts"
version = "49uBK20d"

[[mods]]
type = "modrinth"
id = "architectury-api"
version = "1IiqEQGl"

[[mods]]
type = "modrinth"
id = "curios"
version = "yohfFbgD"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns"
version = "BYUUUeZA"

[[mods]]
type = "modrinth"
id = "when-dungeons-arise"
version = "XIRJSFQ0"

[[mods]]
type = "modrinth"
id = "explorify"
version = "CuBdAr31"

[[mods]]
type = "modrinth"
id = "geckolib"
version = "tPkJmim6"

[[mods]]
type = "modrinth"
id = "gravestone-mod"
version = "3a6KIbgL"

[[mods]]
type = "modrinth"
id = "kotlin-lang-forge"
version = "318K66ba"

[[mods]]
type = "modrinth"
id = "l_enders-cataclysm"
version = "695vQRhD"

[[mods]]
type = "modrinth"
id = "lionfish-api"
version = "fTRMVgyZ"

[[mods]]
type = "modrinth"
id = "manascore"
version = "yhLQMaxS"

[[mods]]
type = "modrinth"
id = "tensura-mysticism"
version = "FuZwNIyc"

[[mods]]
type = "modrinth"
id = "tensura-virtuoso"
version = "DMZ3hO3X"

[[mods]]
type = "modrinth"
id = "open-parties-and-claims"
version = "h4aUy171"

[[mods]]
type = "modrinth"
id = "simply-tensura-addon"
version = "bej1yxrX"

[[mods]]
type = "modrinth"
id = "tensura-slimethrone-extras"
version = "8u8FzhZK"

[[mods]]
type = "modrinth"
id = "smartbrainlib"
version = "O5EpeqI3"

[[mods]]
type = "modrinth"
id = "sophisticated-backpacks"
version = "FHd2LYlQ"

[[mods]]
type = "modrinth"
id = "sophisticated-core"
version = "Yx6FiECq"

[[mods]]
type = "modrinth"
id = "sophisticated-storage"
version = "8A8N1c9A"

[[mods]]
type = "modrinth"
id = "tensura-ep-regen-scaling-reborn"
version = "QQqfzFvd"

[[mods]]
type = "modrinth"
id = "tensura-reincarnated"
version = "uw05A7u2"

[[mods]]
type = "modrinth"
id = "tensura-better-subordinates"
version = "YEHpTlnx"

[[mods]]
type = "modrinth"
id = "tensura-kumodesu"
version = "2oKirX08"

[[mods]]
type = "modrinth"
id = "tensura-skill-obtain"
version = "xfxTkjG7"

[[mods]]
type = "modrinth"
id = "tensura-not-enough-bosses"
version = "yCLL5TdC"

[[mods]]
type = "modrinth"
id = "tensuraepscaling"
version = "36lVoGDh"

[[mods]]
type = "modrinth"
id = "tensura-unique-monsters"
version = "yIJJqKhn"

[[mods]]
type = "modrinth"
id = "terrablender"
version = "6e8GCrLb"

[[mods]]
type = "modrinth"
id = "tr-addon"
version = "XWqOM3lP"

[[mods]]
type = "modrinth"
id = "tensura-arcane"
version = "Y4fJ5Cim"

[[mods]]
type = "modrinth"
id = "tensura-starlight"
version = "i3Q9rxnq"

[[mods]]
type = "modrinth"
id = "veinminer"
version = "syKekkIm"

[[mods]]
type = "modrinth"
id = "veinminer-client"
version = "dIwSWhIM"
