# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.myMachineHardware = {
    config,
    lib,
    pkgs,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/494be6e3-c592-4536-bbf8-22f841665dc2";
      fsType = "ext4";
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/F0C1-1611";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
    
    zramSwap = {
      enable = true;
      algorithm = "zstd";
      memoryPercent = 50;
      priority = 100;
    };

    swapDevices = [
      {
        device = "/dev/disk/by-uuid/871e1acc-2a4e-4ba4-8b88-72ad5bc8a970";
        priority = 100;
      }
    ];
    boot.resumeDevice = "/dev/disk/by-uuid/871e1acc-2a4e-4ba4-8b88-72ad5bc8a970";
    boot.kernel.sysctl."vm.swappiness" = 10;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
